# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: bitnami/laravel:5.8.17
    working_directory: /app
    steps:
      - run: composer require lucascudo/laravel-pt-br-localization
      - run: php artisan vendor:publish --tag=laravel-pt-br-localization
      - run: pwd
      - run: ls
      - run: "[ ! -f resources/lang/pt-BR/auth.php ] && exit 1"
      - run: "[ ! -f resources/lang/pt-BR/pagination.php ] && exit 1"
      - run: "[ ! -f resources/lang/pt-BR/passwords.php ] && exit 1"
      - run: "[ ! -f resources/lang/pt-BR/validation.php ] && exit 1"
      